In [1]:
import os
os.chdir('/Users/jeffreybloodworth/Desktop/git-repos/scRNAseq-ExplainableML')
os.getcwd()

'/Users/jeffreybloodworth/Desktop/git-repos/scRNAseq-ExplainableML'

In [2]:
from pathlib import Path
import pandas as pd

summary = []

for file in Path("data/raw").glob("*metadata*.gz"):

    df = pd.read_csv(file, sep="\t")

    counts = df["is_malignant"].value_counts()

    summary.append({
        "sample": file.name,
        "healthy": counts.get("Healthy", 0),
        "premalignant": counts.get("Premalignant", 0),
        "malignant": counts.get("Malignant", 0),
        "other": counts.get("Other", 0),
        "total_cells": len(df)
    })

summary_df = pd.DataFrame(summary)

summary_df.sort_values(
    "malignant",
    ascending=False
)

,sample,healthy,premalignant,malignant,other,total_cells
10,GSE227690_Pt10Rel_metadata.tsv.gz,0,0,4552,2946,7498
4,GSE227690_Pt16Dx_metadata.tsv.gz,0,0,4117,335,4452
9,GSE227690_Pt15Dx_metadata.tsv.gz,0,0,3057,413,3470
0,GSE227690_Pt12Rel_metadata.tsv.gz,0,0,1190,4125,5315
7,GSE227690_Pt14Dx_metadata.tsv.gz,0,0,1161,6213,7374
2,GSE227690_Pt1Dx_metadata.tsv.gz,0,0,132,2341,2473
11,GSE227690_Pt10Dx_metadata.tsv.gz,0,40,19,10047,10106
5,GSE227690_Pt9Dx_metadata.tsv.gz,0,136,2,4455,4593
6,GSE227690_Pt12Dx_metadata.tsv.gz,0,265,2,6595,6862
1,GSE227690_Pt5Dx_metadata.tsv.gz,0,39,0,4106,4145
3,GSE227690_Pt1Rem_metadata.tsv.gz,0,15,0,10297,10312
8,GSE227690_BM_metadata.tsv.gz,203,0,0,20208,20411

In [3]:
summary_df.to_csv(
    "results/metadata_census.csv",
    index=False
)

In [4]:
pd.crosstab(
    df["CellType"],
    df["is_malignant"]
)

is_malignant    Malignant  Other  Premalignant
CellType
B                       0    182             0
CD4Memory               0   1077             0
CD4Naive                0   1316             0
CD8Memory               0    185             0
CD8Naive                0     42             0
CD8TermExh              0    470             0
EarlyEry                0    183             0
GMP                     0      7             0
GammaDeltaLike          0     60             0
HSPC                    0     43             0
LateEry                 0     87             0
Mono                    0    134             0
NK                      0    168             0
NKT                     0   5854             0
Plasma                  0     30             0
PreB                    0      1             0
ProB                    0      1             0
ProMono                 0     26             0
cDC                     0    146             0
ncMono                  0     35             0
pDC                    19      0            40

In [5]:
from pathlib import Path
import pandas as pd

for file in Path("data/raw").glob("*metadata*.gz"):

    df = pd.read_csv(file, sep="\t")

    print("\n")
    print(file.name)

    print(
        pd.crosstab(
            df["CellType"],
            df["is_malignant"]
        )
    )

GSE227690_Pt12Rel_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       0     33
CD4Memory               1    768
CD4Naive                0     22
CD8Memory               0    120
CD8Naive                0     71
CD8TermExh              0    124
EarlyEry                0     13
GMP                     0      2
GammaDeltaLike          0      8
HSPC                    0      9
LateEry                 0     31
Mono                    1   1708
NK                      2    616
NKT                     2    129
Plasma                 95     44
PreB                    3      3
ProB                   44     11
ProMono                 0    104
cDC                     0     87
ncMono                  1    222
pDC                  1041      0


GSE227690_Pt5Dx_metadata.tsv.gz
is_malignant    Other  Premalignant
CellType
B                 121             0
CD4Memory         722             0
CD4Naive           82             0
CD8Memory         217             0
CD8Naive           37             0
CD8TermExh        348             0
EarlyEry           53             0
GMP                 6             0
GammaDeltaLike     60             0
HSPC               13             0
LateEry            71             0
Mono             1015             0
NK                402             0
NKT               534             0
Plasma              9             0
PreB                1             0
ProB                4             0
ProMono            63             0
cDC               230             0
ncMono            118             0
pDC                 0            39


GSE227690_Pt1Dx_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       0    151
CD4Memory               0    543
CD4Naive                0    163
CD8Memory               0    105
CD8Naive                0     14
CD8TermExh              0    159
EarlyEry                0     12
GammaDeltaLike          0     13
HSPC                    0      9
LateEry                 0      5
Mono                    0      8
NK                      1    692
NKT                     0    420
Plasma                  0      4
ProB                    0      1
ProMono                 0      1
cDC                     0      2
ncMono                  0     39
pDC                   131      0


GSE227690_Pt1Rem_metadata.tsv.gz
is_malignant    Other  Premalignant
CellType
B                 374             0
CD4Memory        3614             0
CD4Naive         1121             0
CD8Memory         466             0
CD8Naive           61             0
CD8TermExh        426             0
EarlyEry           11             0
GammaDeltaLike    136             0
HSPC               23             0
LateEry            27             0
Mono               12             0
NK               2955             0
NKT               987             0
Plasma             11             0
ProB                4             0
ProMono             2             0
cDC                19             0
ncMono             48             0
pDC                 0            15


GSE227690_Pt16Dx_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       1     84
CD4Memory               0      9
CD4Naive                0      2
CD8Memory               0      4
CD8TermExh              0      1
EarlyEry                0      2
GMP                     0      4
GammaDeltaLike          0      1
HSPC                    1     39
LateEry                 0     63
Mono                    0     26
NK                      0     46
NKT                     0     10
Plasma                  6      2
PreB                    5     10
ProB                   72     10
ProMono                 0      4
cDC                     1     13
ncMono                  0      5
pDC                  4031      0


GSE227690_Pt9Dx_metadata.tsv.gz
is_malignant    Malignant  Other  Premalignant
CellType
B                       0    107             0
CD4Memory               0    237             0
CD4Naive                0      5             0
CD8Memory               0     25             0
CD8Naive                0    104             0
CD8TermExh              0     10             0
EarlyEry                0    180             0
GMP                     0     72             0
GammaDeltaLike          0     16             0
HSPC                    0     72             0
LateEry                 0    189             0
Mono                    0   1187             0
NK                      0    276             0
NKT                     0     26             0
Plasma                  0     22             0
ProB                    0      4             0
ProMono                 0   1378             0
cDC                     0    481             0
ncMono                  0     64             0
pDC                     2      0           136


GSE227690_Pt12Dx_metadata.tsv.gz
is_malignant    Malignant  Other  Premalignant
CellType
B                       0    101             0
CD4Memory               0   1169             0
CD4Naive                0    225             0
CD8Memory               0    200             0
CD8Naive                0    198             0
CD8TermExh              0    262             0
EarlyEry                0     62             0
GMP                     0     38             0
GammaDeltaLike          0     25             0
HSPC                    0     79             0
LateEry                 0     60             0
Mono                    0    984             0
NK                      0   1994             0
NKT                     0    440             0
Plasma                  0      6             0
ProB                    0      5             0
ProMono                 0    249             0
cDC                     0    334             0
ncMono                  0    164             0
pDC                     2      0           265


GSE227690_Pt14Dx_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       1    237
CD4Memory               0    967
CD4Naive                0    633
CD8Memory               0    550
CD8Naive                0     35
CD8TermExh              0    528
EarlyEry                0     67
GMP                     0      1
GammaDeltaLike          0     15
HSPC                    0     37
LateEry                 1    450
Mono                    0    154
NK                      1    486
NKT                     5   1812
Plasma                  1     28
PreB                   20     68
ProB                   37     37
ProMono                 0     16
cDC                     0      7
ncMono                  0     85
pDC                  1095      0


GSE227690_BM_metadata.tsv.gz
is_malignant    Healthy  Other
CellType
B                     0   1508
CD4Memory             0   1389
CD4Naive              0   1832
CD8Memory             0    801
CD8Naive              0    779
CD8TermExh            0   1190
EarlyEry              0   1796
GMP                   0    278
GammaDeltaLike        0    261
HSPC                  0    910
LateEry               0   1931
Mono                  0   2555
NK                    0   1371
NKT                   0    626
Plasma                0    228
PreB                  0    194
ProB                  0    534
ProMono               0   1186
cDC                   0    619
ncMono                0    220
pDC                 203      0


GSE227690_Pt15Dx_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       0     74
CD4Memory               0     74
CD4Naive                0      3
CD8Memory               0     52
CD8Naive                0      2
CD8TermExh              1     77
EarlyEry                0      4
GammaDeltaLike          0      2
HSPC                    0      1
LateEry                 5      8
Mono                    0      7
NK                      1     20
NKT                     1     87
Plasma                  0      1
ProB                   20      1
pDC                  3029      0


GSE227690_Pt10Rel_metadata.tsv.gz
is_malignant    Malignant  Other
CellType
B                       0     22
CD4Memory               1    286
CD4Naive                0    132
CD8Memory               0     44
CD8Naive                0     93
CD8TermExh              0     61
EarlyEry                0    220
GMP                     0      2
GammaDeltaLike          0      6
HSPC                    1     31
LateEry                 0     32
Mono                    0     15
NK                     15   1499
NKT                     3    249
Plasma                  0     10
PreB                    6      9
ProB                  133     18
ProMono                 0      1
cDC                     2     11
ncMono                  9    205
pDC                  4382      0


GSE227690_Pt10Dx_metadata.tsv.gz
is_malignant    Malignant  Other  Premalignant
CellType
B                       0    182             0
CD4Memory               0   1077             0
CD4Naive                0   1316             0
CD8Memory               0    185             0
CD8Naive                0     42             0
CD8TermExh              0    470             0
EarlyEry                0    183             0
GMP                     0      7             0
GammaDeltaLike          0     60             0
HSPC                    0     43             0
LateEry                 0     87             0
Mono                    0    134             0
NK                      0    168             0
NKT                     0   5854             0
Plasma                  0     30             0
PreB                    0      1             0
ProB                    0      1             0
ProMono                 0     26             0
cDC                     0    146             0
ncMono                  0     35             0
pDC                    19      0            40